[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    'foundry-huff/=lib/foundry-huff/src/'
]
evm_version = 'shanghai'
ffi = true
optimizer = true
fs_permissions = [{ access = "read", path = "./" }]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
